---
- hosts: angie
  become: yes
  #vars_files:
  #  - secrets.yml
  tasks:
    - name: Обновить систему
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Установить необходимые пакеты
      apt:
        name:
          - build-essential
          - libpcre3
          - libpcre3-dev
          - zlib1g
          - zlib1g-dev
          - openssl
          - libssl-dev

    #- name: Клонировать репозиторий 
    #  git:
    #    #repo: 'https://{{ git_username }}:{{ git_password }}@git.dengisrazy.ru/sa/devops/nginx/angie'
    #    repo: 'https://github.com/webserver-llc/angie' 
    #    dest: '/tmp/angie'

    - name: Создание пользователя angie
      user:
        name: angie
        state: present
  

    - name: Собрать и установить Angie
      shell: |
        cd /tmp/angie
        ./configure --prefix=/etc/angie --conf-path=/etc/angie/angie.conf --error-log-path=/var/log/angie/error.log --http-log-path=/var/log/angie/access.log --lock-path=/run/angie.lock --modules-path=/usr/lib/angie/modules --pid-path=/run/angie.pid --sbin-path=/usr/sbin/angie --http-client-body-temp-path=/var/cache/angie/client_temp --http-fastcgi-temp-path=/var/cache/angie/fastcgi_temp --http-proxy-temp-path=/var/cache/angie/proxy_temp --http-scgi-temp-path=/var/cache/angie/scgi_temp --http-uwsgi-temp-path=/var/cache/angie/uwsgi_temp --user=angie --group=angie --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_v3_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-ld-opt='-DNGX_HTTP_UPSTREAM_CHECK,-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now' --add-module=./nginx_upstream_check_module/ --add-module=./nginx-ntlm-module/
        make
        make install

    - name: Создание директории /var/cache/angie/client_temp
      ansible.builtin.file:
        path: /var/cache/angie/client_temp
        state: directory

    - name: Проверить конфигурацию Angie
      command: /usr/sbin/angie -t
      register: result
      ignore_errors: yes

    - name: Показать результат проверки конфигурации
      debug:
        var: result.stdout_lines

    - name: Перезапустить Angie, если конфигурация в порядке
      command: systemctl restart angie
      when: result.rc == 0